basic_settings:
  site_title: Cian
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/perfil.png
  logo_width: 100

menu_settings:
  menu_items:
    - title: 'Proyectos'
      url: '/'
    - title: 'Blog'
      url: '/blog'
    - title: 'Sobre mi'
      url: '/about'

footer_settings:
 # logo_image: /images/perfil.jpg
  logo_width: 200
  footer_tagline: web de cian para el mundo <3

grid_settings:
  overlay_opacity: 0.7
  grid_spacing: 10

social_settings:
  #twitter_url: ''
  instagram_url: 'http://instagram.com/soycian'
  #snapchat_url: ''
  #youtube_url: ''
  #google-plus_url: ''
  #vimeo_url: ''
  #pinterest_url: ''
  #medium_url: ''
  #quora_url: ''
  #amazon_url: ''
  #apple_url: ''
  #android_url: ''
  #behance_url: ''
  #deviantart_url: ''
  #github_url: ''
  #reddit_url: ''
  #flickr_url: ''
  #etsy_url: ''
  #kickstarter_url: ''
  #soundcloud_url: ''
  #spotify_url: ''
  #bandcamp_url: ''
  #linkedin_url: ''

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#5ea200'
  border_color: '#eeeeee'
  overlay_background_color: '#4e8600'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#2A2F36'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700" rel="stylesheet">'
  title_font: '"Muli", sans-serif'
  body_font: '"Muli", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  grid_item_title:
    small_size: 28
    medium_size: 35
    large_size: 45
    weight: 700
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
